# Generated by Django 5.2.8 on 2026-02-05 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=12)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('qualification', models.CharField(choices=[('B.A,B.Ed - Marathi', 'B.A,B.Ed - Marathi'), ('B.A,B.Ed - Hindi', 'B.A,B.Ed - Hindi'), ('B.A,B.Ed - English', 'B.A,B.Ed - English'), ('B.Sc,B.Ed- Maths', 'B.Sc,B.Ed- Maths'), ('B.Sc,B.Ed- Science', 'B.Sc,B.Ed- Science'), ('B.Sc,B.E/B.Tech- IT', 'B.Sc,B.E/B.Tech- IT'), ('B.A,B.Ed - History', 'B.A,B.Ed - History'), ('BFA,A.T.D / G.D Art-Art', 'BFA,A.T.D / G.D Art-Art'), ('12th Pass', '12th Pass')], max_length=150)),
                ('experience', models.PositiveIntegerField(help_text='In Years')),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subject', models.CharField(blank=True, choices=[('Marathi ', 'Marathi '), ('English', 'English'), ('Hindi', 'Hindi'), ('Mathematics', 'Mathematics'), ('Science & Technology', 'Science & Technology'), ('History', 'History'), ('Civics', 'Civics'), ('Geography', 'Geography'), ('Art Education', 'Art Education')], max_length=150, null=True)),
                ('designation', models.CharField(blank=True, choices=[('Clerk', 'Clerk'), ('Accountant', 'Accountant'), ('Peon', 'Peon'), ('Librarian', 'Librarian'), ('Principal', 'Principal')], max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Staff_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
