# Generated by Django 5.2.8 on 2026-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_employee_id_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
