# Generated by Django 5.2.8 on 2026-02-05 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('occupation', models.CharField(choices=[('Farmer', 'Farmer'), ('Teacher', 'Teacher'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Govt Employee', 'Govt Employee'), ('Pvt Employee', 'PvtEmployee'), ('Businessman', 'Businessman'), ('Shopkeeper', 'Shopkeeper'), ('Driver', 'Driver'), ('Police Officer', 'Police Officer'), ('Army', 'Army'), ('Lawyer', 'Lawyer'), ('Accountant', 'Accountant'), ('Labour', 'Labour'), ('Self Employed', 'Self Employed'), ('Homemaker', 'Homemaker'), ('Retired', 'Retired'), ('Unemployed', 'Unemployed')], max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('caste', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('OTHER', 'OTHER')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Father',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('caste', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('OTHER', 'OTHER')], max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=20)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Others', 'Others')], max_length=50)),
                ('standard', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=150)),
                ('enrollment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('dropped', 'Dropped')], max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Students_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.father')),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
